### PR TITLE
Fix wrong license

### PR DESCRIPTION
**Pull request by disko**
RPL is the „Repoze Public License“, a BSD based license in this case.

**What kind of change does this PR introduce?**

- [ ] Add a project
- [x] Update a project
- [ ] Remove a project
- [ ] Add or update a category
- [ ] Change configuration
- [ ] Documentation
- [ ] Other, please describe:

**Description:**

**Checklist:**

- [x] I have read the [CONTRIBUTING](https://github.com/best-of-lists/best-of/blob/main/CONTRIBUTING.md) guidelines.
- [x] I have not modified the `README.md` file. Projects are only supposed to be added or updated within the `projects.yaml` file since the `README.md` file is automatically generated.

### CODE REVIEW

**Comment by raethlein** [comment]
Hey @disko, thanks for the update! I just compared the license text of RPL with the "standard" BSD licenses and it contains - as the "derived from BSD" suggests - a few different phrases which you might not expect from a standard BSD license. So, I am not sure whether we should update the information here or keep it and leave it to the users of the library to decide whether the license is a right fit, even if that might affect the ranking of the lib in the list.
Probably this is too strict but as this could happen in more cases in the future, it might make sense to at least briefly discuss whether the actual license or the group a license belongs to should be used. @LukasMasuch any thoughts?

**Comment by disko** [comment]
Thanks for your reply @raethlein.

I see the problem. However, the currently associated "Reciprocal Public License" is definitively "more wrong". I tried to submit the "Repopze Public License" to https://tldrlegal.com/, but they're currently not accepting new license submission.

Is it possible to link to https://www.openhub.net/licenses/repoze-public-license or https://github.com/Kotti/Kotti/blob/master/LICENSE.txt instead of just specifying the license's short name?

**Comment by lukasmasuch** [comment]
@disko @raethlein I will add something in the next best-of-generator update to allow setting custom URLs for the license. In the meantime, since @disko seems to be one of the main contributors of Kotti, it is fine from my side to apply this update and temporarily use `BSD` on this list.

**Comment by raethlein** [comment]
@disko @LukasMasuch Alright, I opened an issue [in the generator repo](https://github.com/best-of-lists/best-of-generator/issues/31) and we can merge and close this for now.

**Pull request merged**
